FROM rust:1-bookworm

RUN dpkg --add-architecture arm64 && \
    apt-get update && apt-get install -y --no-install-recommends \
    gcc-aarch64-linux-gnu \
    libc6-dev-arm64-cross \
    libasound2-dev:arm64 \
    libdbus-1-dev:arm64 \
    pkg-config \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER="aarch64-linux-gnu-gcc"
ENV PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/"
ENV PKG_CONFIG_ALLOW_CROSS=1
