use super::sparks_fx_config::{
    default_sparks_fx_selected, sparks_fx_params_map, sparks_fx_target_key, sparks_fx_type,
};
use super::*;

pub(super) struct NativeRunnerConstructionSeed {
    pub(super) now: Instant,
    pub(super) ui: NativeUiState,
    pub(super) hdmi: NativeHdmiConfig,
    pub(super) global_sound: GlobalSoundConfig,
    pub(super) dsp_config: realtime_engine::synth::DspRuntimeConfig,
    pub(super) audio_optimization: AudioOptimization,
    pub(super) audio_optimization_capacity_available: bool,
    pub(super) bpm: f64,
    pub(super) swing_pct: u8,
    pub(super) audio_output_buffer_frames: u32,
    pub(super) sync_source: SyncSource,
    pub(super) algorithm_step_pulses: u32,
    pub(super) instruments: Vec<NativeInstrumentSlot>,
    pub(super) sample_availability: Vec<Vec<NativeSampleAvailability>>,
    pub(super) pulses_layers: Vec<NativePulsesLayer>,
    pub(super) fx_buses: Vec<NativeFxBus>,
    pub(super) global_fx_slots: Vec<String>,
    pub(super) global_fx_params: Vec<Value>,
    pub(super) link_lfos: [NativeLinkLfo; GLOBAL_LFO_COUNT],
    pub(super) param_mods: Vec<NativeParamMods>,
    pub(super) xy_x_binding: Option<NativeParamBinding>,
    pub(super) xy_y_binding: Option<NativeParamBinding>,
    pub(super) aux_auto_map_enabled: bool,
    pub(super) aux_bindings: Vec<Option<NativeAuxBinding>>,
    pub(super) shift_aux_bindings: Vec<Option<NativeAuxBinding>>,
    pub(super) layer_behavior_ids: Vec<String>,
    pub(super) layer_names: Vec<String>,
    pub(super) layer_auto_names: Vec<bool>,
    pub(super) save_grid_states: Vec<bool>,
    pub(super) sample_favourite_dirs: Vec<String>,
    pub(super) sample_builtin_favourite_dirs: Vec<String>,
    pub(super) preset_names: Vec<String>,
    pub(super) midi_outputs: Vec<MidiPort>,
    pub(super) midi_inputs: Vec<MidiPort>,
    pub(super) sparks_mode: String,
    pub(super) sparks_fx_selected: Value,
    pub(super) xy_release: String,
    pub(super) xy_invert_x: bool,
    pub(super) xy_invert_y: bool,
    pub(super) voice_stealing_mode: String,
    pub(super) auto_save_default: bool,
    pub(super) rolling_backups: bool,
    pub(super) input_events_while_paused: bool,
    pub(super) midi_enabled: bool,
    pub(super) midi_clock_out_enabled: bool,
    pub(super) midi_clock_in_enabled: bool,
    pub(super) midi_respond_to_start_stop: bool,
    pub(super) audio_outputs: AudioOutputSet,
    pub(super) jack_audio_required: bool,
    pub(super) usb_midi_out_enabled: bool,
    pub(super) recording_max_minutes: u16,
    pub(super) active_layer_index: usize,
}

impl NativeRunnerConstructionSeed {
    pub(super) fn new(
        config: &NativeRunnerConfig,
        behavior: NativeBehavior,
        ui: NativeUiState,
        now: Instant,
    ) -> Self {
        let behavior_id: String = behavior.id().into();
        Self {
            now,
            ui,
            hdmi: NativeHdmiConfig {
                mode: "none".into(),
                show_gridlines: false,
                cycle_measures: 4,
                source_layer_index: 0,
            },
            global_sound: config.global_sound.clone(),
            dsp_config: realtime_engine::synth::DspRuntimeConfig::default(),
            audio_optimization: config.audio_optimization,
            audio_optimization_capacity_available: config.audio_optimization_capacity_available,
            bpm: config.bpm,
            swing_pct: config.swing_pct.min(75),
            audio_output_buffer_frames: config.audio_output_buffer_frames,
            sync_source: config.sync_source.clone(),
            algorithm_step_pulses: DEFAULT_ALGORITHM_STEP_RED,
            instruments: default_instruments(),
            sample_availability: default_sample_availability(),
            pulses_layers: default_pulses_layers(),
            fx_buses: default_fx_buses(),
            global_fx_slots: default_global_fx_slots(),
            global_fx_params: default_global_fx_params(),
            link_lfos: std::array::from_fn(|_| NativeLinkLfo::default()),
            param_mods: vec![NativeParamMods::default(); LAYER_COUNT],
            xy_x_binding: None,
            xy_y_binding: None,
            aux_auto_map_enabled: true,
            aux_bindings: vec![None; platform_core::AUX_ENCODER_COUNT],
            shift_aux_bindings: vec![None; platform_core::AUX_ENCODER_COUNT],
            layer_behavior_ids: vec![behavior_id.clone(); LAYER_COUNT],
            layer_names: vec![behavior_id; LAYER_COUNT],
            layer_auto_names: vec![true; LAYER_COUNT],
            save_grid_states: vec![true; LAYER_COUNT],
            sample_favourite_dirs: Vec::new(),
            sample_builtin_favourite_dirs: config.sample_builtin_favourite_dirs.clone(),
            preset_names: Vec::new(),
            midi_outputs: Vec::new(),
            midi_inputs: Vec::new(),
            sparks_mode: "mix".into(),
            sparks_fx_selected: default_sparks_fx_selected(),
            xy_release: "sample-hold".into(),
            xy_invert_x: false,
            xy_invert_y: false,
            voice_stealing_mode: "auto-balanced".into(),
            auto_save_default: false,
            rolling_backups: true,
            input_events_while_paused: true,
            midi_enabled: false,
            midi_clock_out_enabled: false,
            midi_clock_in_enabled: false,
            midi_respond_to_start_stop: true,
            audio_outputs: AudioOutputSet::default(),
            jack_audio_required: config.jack_audio_required,
            usb_midi_out_enabled: false,
            recording_max_minutes: 10,
            active_layer_index: 0,
        }
    }

    pub(super) fn initial_menu_config(&self, preset_draft_name: &str) -> NativeMenuConfig {
        NativeMenuConfig {
            behavior_id: self.layer_behavior_ids[self.active_layer_index].clone(),
            behavior_ids: platform_core::list_native_behavior_ids()
                .iter()
                .map(|id| (*id).to_string())
                .collect(),
            worlds_items: vec![],
            worlds_items_by_layer: vec![vec![]; LAYER_COUNT],
            behavior_target_items: vec![vec![]; LAYER_COUNT],
            dsp_config: self.dsp_config,
            layer_labels: self
                .layer_names
                .iter()
                .enumerate()
                .map(|(index, name)| format!("L{}: {name}", index + 1))
                .collect(),
            layer_names: self.layer_names.clone(),
            layer_auto_names: self.layer_auto_names.clone(),
            pulses_layers: pulses_layer_configs(&self.pulses_layers),
            active_layer_index: self.active_layer_index,
            link_lfos: self.link_lfos.clone().map(|lfo| NativeLinkLfoConfig {
                enabled: lfo.enabled,
                target: lfo.target.as_ref().map(param_binding_spec_from_native),
                period: lfo.period,
                depth_pct: lfo.depth_pct,
            }),
            param_mods: param_mod_configs(&self.param_mods),
            xy_x_binding: self
                .xy_x_binding
                .as_ref()
                .map(param_binding_spec_from_native),
            xy_y_binding: self
                .xy_y_binding
                .as_ref()
                .map(param_binding_spec_from_native),
            aux_auto_map_enabled: self.aux_auto_map_enabled,
            aux_bindings: aux_binding_configs(&self.aux_bindings),
            shift_aux_bindings: aux_binding_configs(&self.shift_aux_bindings),
            instrument_labels: instrument_labels(&self.instruments),
            instrument_names: instrument_names(&self.instruments),
            instrument_types: instrument_types(&self.instruments),
            instrument_auto_names: instrument_auto_names(&self.instruments),
            instrument_note_behaviors: instrument_note_behaviors(&self.instruments),
            instrument_routes: instrument_routes(&self.instruments),
            instrument_volumes: instrument_volumes(&self.instruments),
            instrument_pan_positions: instrument_pan_positions(&self.instruments),
            instrument_sample_slots: instrument_sample_slots(&self.instruments),
            instrument_sample_paths: instrument_sample_paths(&self.instruments),
            instrument_sample_availability: self.sample_availability.clone(),
            instrument_synth_configs: instrument_synth_configs(&self.instruments),
            instrument_synth_osc1_waveforms: instrument_synth_osc1_waveforms(&self.instruments),
            instrument_synth_osc2_waveforms: instrument_synth_osc2_waveforms(&self.instruments),
            instrument_synth_filter_types: instrument_synth_filter_types(&self.instruments),
            instrument_synth_filter_cutoffs: instrument_synth_filter_cutoffs(&self.instruments),
            instrument_synth_gain_pct: instrument_synth_gain_pct(&self.instruments),
            instrument_synth_filter_resonance: instrument_synth_filter_resonance(&self.instruments),
            instrument_sample_tune_semis: instrument_sample_tune_semis(&self.instruments),
            instrument_sample_gain_pct: instrument_sample_gain_pct(&self.instruments),
            instrument_sample_base_velocity: instrument_sample_base_velocity(&self.instruments),
            instrument_sample_amp_velocity_sensitivity_pct:
                instrument_sample_amp_velocity_sensitivity_pct(&self.instruments),
            instrument_sample_velocity_levels_enabled: instrument_sample_velocity_levels_enabled(
                &self.instruments,
            ),
            instrument_sample_velocity_high: instrument_sample_velocity_high(&self.instruments),
            instrument_sample_velocity_medium: instrument_sample_velocity_medium(&self.instruments),
            instrument_sample_velocity_low: instrument_sample_velocity_low(&self.instruments),
            instrument_sample_amp_envs: instrument_sample_amp_envs(&self.instruments),
            instrument_sample_filters: instrument_sample_filters(&self.instruments),
            instrument_sample_filter_envs: instrument_sample_filter_envs(&self.instruments),
            instrument_midi_enabled: instrument_midi_enabled(&self.instruments),
            instrument_midi_channels: instrument_midi_channels(&self.instruments),
            instrument_midi_velocity: instrument_midi_velocity(&self.instruments),
            instrument_midi_duration_ms: instrument_midi_duration_ms(&self.instruments),
            fx_buses: fx_bus_configs(&self.fx_buses),
            global_fx_slots: self.global_fx_slots.clone(),
            global_fx_params: self.global_fx_params.clone(),
            sample_browser: None,
            sample_favourite_dirs: self.sample_favourite_dirs.clone(),
            sample_builtin_favourite_dirs: self.sample_builtin_favourite_dirs.clone(),
            algorithm_step_pulses: self.algorithm_step_pulses,
            master_volume: self.ui.master_volume,
            note_length_ms: self.global_sound.note_length_ms as u16,
            velocity_scale_pct: self.global_sound.velocity_scale_pct,
            velocity_curve: velocity_curve_id(self.global_sound.velocity_curve).into(),
            voice_stealing_mode: self.voice_stealing_mode.clone(),
            auto_save_default: self.auto_save_default,
            rolling_backups: self.rolling_backups,
            ghost_cells: self.ui.ghost_cells,
            input_events_while_paused: self.input_events_while_paused,
            numeric_display_mode: self.ui.numeric_display_mode.clone(),
            screen_sleep_seconds: self.ui.screen_sleep_seconds,
            dim_timer_seconds: self.ui.dim_timer_seconds,
            grid_brightness: self.ui.grid_brightness,
            display_brightness: self.ui.display_brightness,
            button_brightness: self.ui.button_brightness,
            midi_enabled: self.midi_enabled,
            midi_clock_out_enabled: self.midi_clock_out_enabled,
            midi_clock_in_enabled: self.midi_clock_in_enabled,
            midi_respond_to_start_stop: self.midi_respond_to_start_stop,
            audio_outputs: self.audio_outputs,
            jack_audio_required: self.jack_audio_required,
            audio_optimization: self.audio_optimization,
            audio_optimization_capacity_available: self.audio_optimization_capacity_available,
            usb_midi_out_enabled: self.usb_midi_out_enabled,
            recording_max_minutes: self.recording_max_minutes,
            hdmi_mode: self.hdmi.mode.clone(),
            hdmi_show_gridlines: self.hdmi.show_gridlines,
            hdmi_cycle_measures: self.hdmi.cycle_measures,
            preset_names: self.preset_names.clone(),
            preset_draft_name: preset_draft_name.into(),
            preset_rename_source: None,
            midi_outputs: self
                .midi_outputs
                .iter()
                .map(|port| (port.id.clone(), port.name.clone()))
                .collect(),
            midi_inputs: self
                .midi_inputs
                .iter()
                .map(|port| (port.id.clone(), port.name.clone()))
                .collect(),
            sparks_mode: self.sparks_mode.clone(),
            sparks_fx_type: sparks_fx_type(&self.sparks_fx_selected).into(),
            sparks_fx_target: sparks_fx_target_key(&self.sparks_fx_selected).into(),
            sparks_fx_params: sparks_fx_params_map(&self.sparks_fx_selected),
            xy_release: self.xy_release.clone(),
            xy_invert_x: self.xy_invert_x,
            xy_invert_y: self.xy_invert_y,
            bpm: crate::delay_timing::visible_bpm_u16(self.bpm),
            swing_pct: self.swing_pct,
            audio_output_buffer_frames: self.audio_output_buffer_frames,
            sync_source: self.sync_source.clone(),
        }
    }
}
