import type {
  RuntimeAudioCommand,
  RuntimePlatformEffect,
  RuntimeSetupPortalStatus,
  RuntimeStoreResult,
  RuntimeUserDataTransferStatus,
} from "../src/index";

export const RUNTIME_AUDIO_COMMAND_FIXTURES = [
  {
    type: "set_audio_config",
    revision: 2,
    config: { sampleRate: 44100, blockFrames: 256 },
  },
  { type: "set_master_volume", volumePct: 82 },
  {
    type: "set_instrument_mixer",
    instrumentSlot: 1,
    volumePct: 74,
    panPos: 16,
  },
  { type: "set_fx_bus_mixer", busIndex: 2, panPos: 12, volumePct: 66 },
  {
    type: "set_synth_param",
    instrumentSlot: 3,
    path: "osc.cutoff",
    value: 0.7,
  },
  {
    type: "set_sample_bank_param",
    instrumentSlot: 4,
    path: "slot.0.level",
    value: 0.8,
  },
  {
    type: "set_fx_bus_slot",
    busIndex: 1,
    slotIndex: 0,
    fxType: "delay",
    params: { mix: 0.35 },
  },
  {
    type: "set_global_fx_slot",
    slotIndex: 1,
    fxType: "compressor",
    params: { threshold: -12 },
  },
  {
    type: "momentary_fx_start",
    id: "spark:0",
    fxType: "freeze",
    params: { amount: 1 },
    target: { type: "fx_bus", index: 0 },
  },
  { type: "momentary_fx_update", id: "spark:0", params: { amount: 0.5 } },
  { type: "momentary_fx_stop", id: "spark:0" },
  {
    type: "sample_preview",
    instrumentSlot: 5,
    sampleSlot: 2,
    path: "kits/hat.wav",
    velocity: 96,
  },
] as const satisfies readonly RuntimeAudioCommand[];

export const RUNTIME_PLATFORM_EFFECT_FIXTURES = [
  { type: "store_list_presets" },
  { type: "store_load_preset", name: "Factory" },
  {
    type: "store_save_preset",
    name: "Jam",
    payload: { bpm: 120 },
    mode: "deferred",
  },
  { type: "store_delete_preset", name: "Old Jam" },
  { type: "store_load_default" },
  { type: "store_save_default", payload: { bpm: 96 }, mode: "immediate" },
  { type: "store_save_backup", payload: { name: "backup" } },
  { type: "store_save_recovery", payload: { dirty: true } },
  { type: "midi_list_outputs_request" },
  { type: "midi_list_inputs_request" },
  { type: "midi_select_output", id: "out-1" },
  { type: "midi_select_input", id: null },
  { type: "midi_panic" },
  { type: "reboot" },
  { type: "shutdown" },
  { type: "hardware_test" },
  { type: "update_check" },
  { type: "update_apply" },
  { type: "rollback" },
  { type: "system_info_request" },
  { type: "setup_portal_open" },
  { type: "user_data_transfer_open" },
  { type: "user_data_transfer_close" },
  {
    type: "sample_list_request",
    instrumentSlot: 0,
    sampleSlot: 7,
    dir: "samples",
  },
  { type: "audio_command", command: RUNTIME_AUDIO_COMMAND_FIXTURES[0] },
] as const satisfies readonly RuntimePlatformEffect[];

export const RUNTIME_SETUP_PORTAL_STATUS_FIXTURES = [
  {
    type: "setup_portal_status",
    phase: "starting",
    disposition: "accepted",
    rebootRequired: false,
  },
  {
    type: "setup_portal_status",
    phase: "starting",
    disposition: "already_running",
    rebootRequired: false,
  },
  {
    type: "setup_portal_status",
    phase: "portal_ready",
    portalSuffix: "abcd",
    rebootRequired: false,
  },
  { type: "setup_portal_status", phase: "finalizing", rebootRequired: false },
  { type: "setup_portal_status", phase: "succeeded", rebootRequired: false },
  {
    type: "setup_portal_status",
    phase: "failed",
    rebootRequired: false,
    errorCode: "operation_failed",
  },
  {
    type: "setup_portal_status",
    phase: "failed",
    rebootRequired: false,
    errorCode: "invalid_payload",
  },
  {
    type: "setup_portal_status",
    phase: "failed",
    rebootRequired: false,
    errorCode: "unavailable",
  },
  {
    type: "setup_portal_status",
    phase: "timed_out",
    rebootRequired: false,
    errorCode: "unavailable",
  },
  {
    type: "setup_portal_status",
    phase: "unsupported",
    rebootRequired: false,
    errorCode: "unsupported",
  },
] as const satisfies readonly RuntimeSetupPortalStatus[];

export const RUNTIME_USER_DATA_TRANSFER_STATUS_FIXTURES = [
  {
    type: "user_data_transfer_status",
    phase: "ready",
    url: "http://192.168.42.1:8081",
    code: "Ab2Cd3Ef4G",
    expiresInSeconds: 900,
  },
  { type: "user_data_transfer_status", phase: "closed" },
  { type: "user_data_transfer_status", phase: "unsupported" },
] as const satisfies readonly RuntimeUserDataTransferStatus[];

export const RUNTIME_STORE_RESULT_FIXTURES = [
  { type: "list_presets_result", names: ["Factory", "Live Set"] },
  { type: "load_preset_result", name: "Factory", payload: { layers: [] } },
  { type: "save_preset_result", name: "Live Set", outcome: "overwritten" },
  { type: "delete_preset_result", name: "Scratch", ok: true },
  { type: "load_default_result", payload: null },
  { type: "save_default_result", ok: true, isAuto: true },
  { type: "save_backup_result", ok: true },
  { type: "save_recovery_result", ok: false },
  { type: "store_error", message: "disk full" },
  {
    type: "runtime_failure",
    error: {
      domain: "audio",
      code: "audio_thread_failed",
      operation: "audio_thread",
      message: "thread stopped",
    },
  },
  {
    type: "identified",
    result: { type: "list_presets_result", names: ["Factory"] },
    requestId: "platform-1",
    revision: 3,
  },
  {
    type: "operation_succeeded",
    operation: "store_load_default",
    requestId: "load-default-1",
    revision: 4,
  },
  {
    type: "midi_list_outputs_result",
    outputs: [{ id: "out-1", name: "Octessera MIDI" }],
  },
  {
    type: "midi_list_inputs_result",
    inputs: [{ id: "in-1", name: "Clock In" }],
  },
  {
    type: "midi_status",
    ok: false,
    message: "not connected",
    selectedOutId: null,
    selectedInId: "in-1",
  },
  {
    type: "sample_list_result",
    instrumentSlot: 2,
    sampleSlot: 3,
    dir: "samples",
    entries: [{ name: "Kicks", path: "samples/Kicks", isDir: true }],
  },
  {
    type: "sample_list_error",
    instrumentSlot: 2,
    sampleSlot: 3,
    dir: "samples",
    message: "permission denied",
  },
  { type: "sample_preview_error", message: "unsupported format" },
  { type: "device_update_status", ok: false, message: "opaque helper output" },
  {
    type: "system_info_result",
    info: {
      os: "linux",
      osVersion: "6.6",
      octesseraVersion: "0.7.0",
      primaryIp: "192.168.1.5",
      primaryMac: "aa:bb:cc:dd:ee:ff",
      hostname: "octessera",
      boardProfile: "raspberry-pi-zero-2w",
    },
  },
  {
    type: "system_info_error",
    error: { code: "unavailable", message: "not connected" },
  },
  RUNTIME_SETUP_PORTAL_STATUS_FIXTURES[0],
  RUNTIME_USER_DATA_TRANSFER_STATUS_FIXTURES[0],
  {
    type: "identified",
    result: {
      type: "setup_portal_status",
      phase: "succeeded",
      rebootRequired: false,
    },
    requestId: "setup-portal-1",
    revision: 9,
  },
] as const satisfies readonly RuntimeStoreResult[];
