use super::binding_tree::binding_action;
use super::{group, NativeMenuConfig, NativeMenuItem, NativeValueLaneConfig};

pub(super) fn sense_binding_group(
    index: usize,
    label: &str,
    config: &NativeMenuConfig,
    target: &str,
) -> Option<NativeMenuItem> {
    let sense = config.sense_parts.get(index)?;
    let prefix = format!("parts.{index}.l2");
    Some(group(
        label,
        vec![
            group(
                "Scanning",
                vec![
                    binding_action(
                        "Scan Mode",
                        &format!("{prefix}.scanMode"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["none", "scanning"],
                        target,
                    ),
                    binding_action(
                        "Scan Axis",
                        &format!("{prefix}.scanAxis"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["rows", "columns"],
                        target,
                    ),
                    binding_action(
                        "Scan Unit",
                        &format!("{prefix}.scanUnit"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["1/16", "1/8", "1/4", "1/2", "1/1"],
                        target,
                    ),
                    binding_action(
                        "Scan Direction",
                        &format!("{prefix}.scanDirection"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["forward", "reverse"],
                        target,
                    ),
                    binding_action(
                        "Sections",
                        &format!("{prefix}.scanSections"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["1", "2", "4", "8"],
                        target,
                    ),
                ],
            ),
            group(
                "Events",
                vec![
                    binding_action(
                        "Event Triggers",
                        &format!("{prefix}.eventEnabled"),
                        "bool",
                        None,
                        None,
                        None,
                        vec![],
                        target,
                    ),
                    binding_action(
                        "State Notes",
                        &format!("{prefix}.stateNotesEnabled"),
                        "bool",
                        None,
                        None,
                        None,
                        vec![],
                        target,
                    ),
                ],
            ),
            group(
                "Trigger Prob.",
                vec![
                    binding_action(
                        "Mode",
                        &format!("{prefix}.triggerProbabilityMode"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["zero", "custom", "full"],
                        target,
                    ),
                    binding_action(
                        "Low Prob",
                        &format!("{prefix}.triggerProbabilityLowPct"),
                        "number",
                        Some(0),
                        Some(100),
                        Some(1),
                        vec![],
                        target,
                    ),
                    binding_action(
                        "High Prob",
                        &format!("{prefix}.triggerProbabilityHighPct"),
                        "number",
                        Some(0),
                        Some(100),
                        Some(1),
                        vec![],
                        target,
                    ),
                ],
            ),
            group(
                "Note Mapping",
                vec![
                    binding_action(
                        "Low Note",
                        &format!("{prefix}.pitch.lowestNote"),
                        "number",
                        Some(0),
                        Some(127),
                        Some(1),
                        vec![],
                        target,
                    ),
                    binding_action(
                        "High Note",
                        &format!("{prefix}.pitch.highestNote"),
                        "number",
                        Some(0),
                        Some(127),
                        Some(1),
                        vec![],
                        target,
                    ),
                    binding_action(
                        "Start Note",
                        &format!("{prefix}.pitch.startingNote"),
                        "number",
                        Some(0),
                        Some(127),
                        Some(1),
                        vec![],
                        target,
                    ),
                    binding_action(
                        "Scale",
                        &format!("{prefix}.pitch.scale"),
                        "enum",
                        None,
                        None,
                        None,
                        vec![
                            "chromatic",
                            "major",
                            "natural_minor",
                            "dorian",
                            "mixolydian",
                            "major_pentatonic",
                            "minor_pentatonic",
                            "harmonic_minor",
                        ],
                        target,
                    ),
                    binding_action(
                        "Root",
                        &format!("{prefix}.pitch.root"),
                        "enum",
                        None,
                        None,
                        None,
                        vec![
                            "C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",
                        ],
                        target,
                    ),
                    binding_action(
                        "Out of Range",
                        &format!("{prefix}.pitch.outOfRange"),
                        "enum",
                        None,
                        None,
                        None,
                        vec!["clamp", "wrap"],
                        target,
                    ),
                ],
            ),
            sense_axis_binding_group(&format!("{prefix}.x"), "X Axis", target),
            sense_axis_lane_binding_group(
                &format!("{prefix}.x.velocity"),
                "Velocity",
                &sense.x_velocity,
                target,
            ),
            sense_axis_lane_binding_group(
                &format!("{prefix}.x.filterCutoff"),
                "Filter Cutoff",
                &sense.x_filter_cutoff,
                target,
            ),
            sense_axis_lane_binding_group(
                &format!("{prefix}.x.filterResonance"),
                "Filter Resonance",
                &sense.x_filter_resonance,
                target,
            ),
            sense_axis_binding_group(&format!("{prefix}.y"), "Y Axis", target),
            sense_axis_lane_binding_group(
                &format!("{prefix}.y.velocity"),
                "Velocity",
                &sense.y_velocity,
                target,
            ),
            sense_axis_lane_binding_group(
                &format!("{prefix}.y.filterCutoff"),
                "Filter Cutoff",
                &sense.y_filter_cutoff,
                target,
            ),
            sense_axis_lane_binding_group(
                &format!("{prefix}.y.filterResonance"),
                "Filter Resonance",
                &sense.y_filter_resonance,
                target,
            ),
        ],
    ))
}

fn sense_axis_binding_group(prefix: &str, label: &str, target: &str) -> NativeMenuItem {
    group(
        label,
        vec![group(
            "Pitch Steps",
            vec![
                binding_action(
                    "Enabled",
                    &format!("{prefix}.pitch.enabled"),
                    "bool",
                    None,
                    None,
                    None,
                    vec![],
                    target,
                ),
                binding_action(
                    "Steps",
                    &format!("{prefix}.pitch.steps"),
                    "number",
                    Some(-16),
                    Some(16),
                    Some(1),
                    vec![],
                    target,
                ),
                binding_action(
                    "Restart Section",
                    &format!("{prefix}.pitch.restartEachSection"),
                    "bool",
                    None,
                    None,
                    None,
                    vec![],
                    target,
                ),
            ],
        )],
    )
}

fn sense_axis_lane_binding_group(
    prefix: &str,
    label: &str,
    lane: &NativeValueLaneConfig,
    target: &str,
) -> NativeMenuItem {
    let _ = lane;
    group(
        label,
        vec![
            binding_action(
                "Enabled",
                &format!("{prefix}.enabled"),
                "bool",
                None,
                None,
                None,
                vec![],
                target,
            ),
            binding_action(
                "From",
                &format!("{prefix}.from"),
                "number",
                Some(0),
                Some(127),
                Some(1),
                vec![],
                target,
            ),
            binding_action(
                "To",
                &format!("{prefix}.to"),
                "number",
                Some(0),
                Some(127),
                Some(1),
                vec![],
                target,
            ),
            binding_action(
                "Grid Offs",
                &format!("{prefix}.gridOffset"),
                "number",
                Some(-7),
                Some(7),
                Some(1),
                vec![],
                target,
            ),
            binding_action(
                "Curve",
                &format!("{prefix}.curve"),
                "enum",
                None,
                None,
                None,
                vec!["linear", "exp", "log"],
                target,
            ),
        ],
    )
}
