[package]
name = "rodio-engine-source"
version = "0.8.2"
edition = "2021"
license-file.workspace = true

[lib]
path = "src/lib.rs"

[features]
source-worker-benchmark-timing = ["realtime-engine/source-worker-benchmark-timing"]
routing-tree-benchmark = ["realtime-engine/routing-tree-benchmark"]
benchmark-voice-pools-128 = ["realtime-engine/benchmark-voice-pools-128"]
benchmark-voice-pools-256 = ["realtime-engine/benchmark-voice-pools-256"]

[dependencies]
crossbeam-channel = "0.5"
hound = "3.5"
realtime-engine = { path = "../realtime-engine" }
rodio = "0.20"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
realtime-engine = { path = "../realtime-engine", features = ["test-support"] }
