#!/bin/sh
set -e

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "${1:-}" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/local/bin/octessera-pi /usr/local/bin/octessera-pi
copy_exec /usr/bin/setsid /usr/bin/setsid
copy_exec /bin/sh /bin/sh
copy_exec /bin/sleep /bin/sleep
copy_exec /bin/cat /bin/cat
copy_exec /bin/mv /bin/mv
copy_exec /bin/chmod /bin/chmod
copy_exec /bin/chown /bin/chown
copy_exec /bin/rm /bin/rm
manual_add_modules spi-bcm2835 || true
manual_add_modules spidev || true
