#!/bin/sh
set -e

PREREQ=""

prereqs() {
    echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/local/bin/octessera-pi /usr/local/bin/octessera-pi
manual_add_modules spi-bcm2835 || true
manual_add_modules spidev || true
