// Generated by tools/resources/generate-display-palette.mjs from resources/display-palette.json.
// Do not edit by hand.

export type DisplayPaletteRgb = readonly [number, number, number];

export const DISPLAY_PALETTE = {
  "worlds": {
    "label": "Worlds",
    "hex": "#63D23F",
    "rgb": [
      99,
      210,
      63
    ],
    "rgb565": 26247
  },
  "pulses": {
    "label": "Pulses",
    "hex": "#E077CC",
    "rgb": [
      224,
      119,
      204
    ],
    "rgb565": 58297
  },
  "tones": {
    "label": "Tones",
    "hex": "#35CFF2",
    "rgb": [
      53,
      207,
      242
    ],
    "rgb565": 13950
  },
  "sparks": {
    "label": "Sparks",
    "hex": "#FFD447",
    "rgb": [
      255,
      212,
      71
    ],
    "rgb565": 65192
  },
  "system": {
    "label": "System",
    "hex": "#C9CED6",
    "rgb": [
      201,
      206,
      214
    ],
    "rgb565": 52858
  },
  "white": {
    "label": "White",
    "hex": "#FFFFFF",
    "rgb": [
      255,
      255,
      255
    ],
    "rgb565": 65535
  },
  "black": {
    "label": "Black",
    "hex": "#000000",
    "rgb": [
      0,
      0,
      0
    ],
    "rgb565": 0
  }
} as const;

export const WORLDS_COLOR = DISPLAY_PALETTE.worlds.rgb;
export const PULSES_COLOR = DISPLAY_PALETTE.pulses.rgb;
export const TONES_COLOR = DISPLAY_PALETTE.tones.rgb;
export const SPARKS_COLOR = DISPLAY_PALETTE.sparks.rgb;
export const SYSTEM_COLOR = DISPLAY_PALETTE.system.rgb;
export const WHITE_COLOR = DISPLAY_PALETTE.white.rgb;
export const BLACK_COLOR = DISPLAY_PALETTE.black.rgb;
