// Generated by tools/resources/generate-display-palette.mjs from resources/display-palette.json.
// Do not edit by hand.

export type DisplayPaletteRgb = readonly [number, number, number];

export const DISPLAY_PALETTE = {
  "green": {
    "label": "Green",
    "hex": "#63D23F",
    "rgb": [
      99,
      210,
      63
    ],
    "rgb565": 26247
  },
  "red": {
    "label": "Red",
    "hex": "#DD82CD",
    "rgb": [
      221,
      130,
      205
    ],
    "rgb565": 56345
  },
  "blue": {
    "label": "Blue",
    "hex": "#35CFF2",
    "rgb": [
      53,
      207,
      242
    ],
    "rgb565": 13950
  },
  "yellow": {
    "label": "Yellow",
    "hex": "#FFD447",
    "rgb": [
      255,
      212,
      71
    ],
    "rgb565": 65192
  },
  "gray": {
    "label": "Gray",
    "hex": "#C9CED6",
    "rgb": [
      201,
      206,
      214
    ],
    "rgb565": 52858
  },
  "white": {
    "label": "White",
    "hex": "#FFFFFF",
    "rgb": [
      255,
      255,
      255
    ],
    "rgb565": 65535
  },
  "black": {
    "label": "Black",
    "hex": "#000000",
    "rgb": [
      0,
      0,
      0
    ],
    "rgb565": 0
  }
} as const;

export const GREEN_COLOR = DISPLAY_PALETTE.green.rgb;
export const RED_COLOR = DISPLAY_PALETTE.red.rgb;
export const BLUE_COLOR = DISPLAY_PALETTE.blue.rgb;
export const YELLOW_COLOR = DISPLAY_PALETTE.yellow.rgb;
export const GRAY_COLOR = DISPLAY_PALETTE.gray.rgb;
export const WHITE_COLOR = DISPLAY_PALETTE.white.rgb;
export const BLACK_COLOR = DISPLAY_PALETTE.black.rgb;
