// Generated by tools/resources/generate-platform-capabilities.mjs from resources/platform-capabilities.json.
// Do not edit by hand.

export const PLATFORM_CAPS = {
  "gridWidth": 8,
  "gridHeight": 8,
  "partCount": 8,
  "instrumentCount": 8,
  "sampleSlotCount": 8,
  "audioSampleRate": 44100,
  "audioBlockFrames": 128,
  "maxSynthVoices": 16,
  "maxSampleVoices": 64,
  "maxSynthVoicesPerSlot": 8,
  "maxSampleVoicesPerSlot": 8,
  "busFxWarningSlotCount": 6,
  "busCount": 4,
  "globalFxSlotCount": 2,
  "auxEncoderCount": 3,
  "touchFxMaxConcurrent": 2,
  "scanSectionCounts": [
    1,
    2,
    4,
    8
  ],
  "panPositionCount": 33,
  "oledWidth": 128,
  "oledHeight": 128
} as const;

export const GRID_WIDTH = PLATFORM_CAPS.gridWidth;
export const GRID_HEIGHT = PLATFORM_CAPS.gridHeight;
export const PAN_POSITION_COUNT = PLATFORM_CAPS.panPositionCount;
export const AUX_ENCODER_COUNT = PLATFORM_CAPS.auxEncoderCount;
export const OLED_WIDTH = PLATFORM_CAPS.oledWidth;
export const OLED_HEIGHT = PLATFORM_CAPS.oledHeight;
