# shellcheck shell=bash
# Check definitions for tools/quality/pre-push.sh. Sourced, not executed.
# Defines run_pre_push_checks <profile> which calls the runner's run_check command executor.

check_file_length() {
  local root max=500 failed=0 file rel lines name first_line
  root="$(git rev-parse --show-toplevel)"
  while IFS= read -r -d '' file; do
    rel="${file#"$root"/}"
    name="${file##*/}"
    case "$name" in
      *.bash|*.js|*.mjs|*.ps1|*.psm1|*.py|*.rs|*.sh|*.ts|*.tsx) ;;
      .*.*|?*.*) continue ;;
      *)
        case "$rel" in
          tools/pi-image/stage3-octessera-kernel/files/root/usr/local/sbin/*|\
          tools/pi-image/stage4-octessera/files/root/etc/initramfs-tools/hooks/*|\
          tools/pi-image/stage4-octessera/files/root/etc/initramfs-tools/scripts/*|\
          tools/pi-image/stage4-octessera/files/root/usr/local/bin/*|\
          tools/pi-image/stage4-octessera/files/root/usr/local/sbin/*|\
          userpatches/overlay/etc/initramfs-tools/hooks/*|\
          userpatches/overlay/etc/initramfs-tools/scripts/*|\
          userpatches/overlay/usr/local/sbin/*) ;;
          *)
            first_line=
            IFS= read -r first_line < "$file" || true
            [[ "$first_line" == '#!'* ]] || continue
            ;;
        esac
        ;;
    esac
    lines="$(wc -l < "$file")"
    if [ -s "$file" ] && [ "$(tail -c 1 "$file" | wc -l)" -eq 0 ]; then
      lines=$((lines + 1))
    fi
    if [ "$lines" -gt "$max" ]; then
      printf '  ✗ %s (%s lines, max %s)\n' "$rel" "$lines" "$max" >&2
      failed=1
    fi
  done < <(find "$root" \
    \( -type d \( \
      -name '.git' -o -name '.mypy_cache' -o -name '.opencode' -o \
      -name '.pnpm-store' -o \
      -name '.pytest_cache' -o -name '.ruff_cache' -o -name '.turbo' -o \
      -name '.slim' -o -name '.venv' -o -name '__pycache__' -o \
      -name 'artifacts' -o \
      -name 'autogenerated' -o -name 'build' -o -name 'clonedeps' -o \
      -name 'coverage' -o -name 'debug' -o -name 'diagnostics' -o \
      -name 'dist' -o -name 'gen' -o -name 'generated' -o -name 'node_modules' -o \
      -name 'release-artifacts' -o -name 'release-legal' -o \
      -name 'release-samples' -o -name 'signalsmith-stretch' -o \
      -name 'target' -o -name 'third_party' -o -name 'tmp' -o -name 'vendor' \
    \) -prune \) -o \
    \( -type d -path '*/hardware/enclosure/review' -prune \) -o \
    \( -type d -path '*/hardware/pcb/gerber' -prune \) -o \
    \( -type f \( \
      -name '*.bash' -o -name '*.js' -o -name '*.mjs' -o -name '*.ps1' -o \
      -name '*.psm1' -o -name '*.py' -o -name '*.rs' -o -name '*.sh' -o \
      -name '*.ts' -o -name '*.tsx' -o ! -name '*.*' -o -name '.*' \
    \) -print0 \))
  return "$failed"
}

run_pre_push_checks() {
  local profile="$1"
  if [ "$profile" = fast ]; then
    run_check "pnpm lint" corepack pnpm run lint
    run_check "pnpm typecheck" corepack pnpm run typecheck
    run_check "pnpm format:check" corepack pnpm run format:check
    run_check "cargo fmt" cargo fmt --all --check
    run_check "file length" check_file_length
    return 0
  fi

  run_check "pnpm lint" corepack pnpm run lint
  run_check "pnpm typecheck" corepack pnpm run typecheck
  run_check "pnpm format:check" corepack pnpm run format:check
  run_check "pnpm test" corepack pnpm run test
  run_check "pnpm test:coverage" corepack pnpm run test:coverage
  run_check "cargo fmt" cargo fmt --all --check
  run_check "file length" check_file_length
  run_check "cargo test" \
    cargo test --workspace --exclude octessera-desktop --exclude rodio-engine-source
  run_check "enum help coverage" \
    cargo test -p playback-runtime native_menu::tests::help_enum_tests
  run_check "factory patch UI scenario" \
    cargo test -p playback-runtime factory_patch_ui_scenario -- --ignored
  run_check "cargo llvm-cov" bash ./tools/quality/check-rust-coverage.sh
  run_check "stage desktop legal resources" corepack pnpm run legal:stage-desktop
  run_check "cargo check desktop" cargo check -p octessera-desktop
  run_check "cargo test desktop" cargo test -p octessera-desktop
  run_check "cargo check pi" cargo check -p octessera-pi
  run_check "tauri build smoke" corepack pnpm run tauri:build:ci
  run_check "cargo clippy" \
    cargo clippy --workspace --exclude octessera-desktop --exclude rodio-engine-source \
    --all-targets -- -D warnings
}
