import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { extname, join, relative, resolve } from "node:path";
import {
  scanApproximateRustFunctions,
  scanJavaScriptFunctions,
} from "./quality-audit-parser.mjs";

const ROOT = resolve(process.cwd());
const INCLUDE_EXT = new Set([
  ".bash",
  ".js",
  ".mjs",
  ".ps1",
  ".psm1",
  ".py",
  ".rs",
  ".sh",
  ".ts",
  ".tsx",
]);
const JAVASCRIPT_EXT = new Set([".js", ".mjs", ".ts", ".tsx"]);
const IGNORE_DIRS = new Set([
  ".git",
  ".mypy_cache",
  ".opencode",
  ".pnpm-store",
  ".pytest_cache",
  ".ruff_cache",
  ".slim",
  ".turbo",
  ".venv",
  "__pycache__",
  "artifacts",
  "autogenerated",
  "build",
  "clonedeps",
  "coverage",
  "debug",
  "diagnostics",
  "dist",
  "gen",
  "generated",
  "node_modules",
  "release-artifacts",
  "release-legal",
  "release-samples",
  "signalsmith-stretch",
  "target",
  "third_party",
  "tmp",
  "vendor",
]);
const EXCLUDED_AUDIT_ROOTS = new Set([
  "hardware/enclosure/review",
  "hardware/pcb/gerber",
]);
const DEPLOYMENT_SCRIPT_ROOTS = new Set([
  "tools/pi-image/stage3-octessera-kernel/files/root/usr/local/sbin",
  "tools/pi-image/stage4-octessera/files/root/etc/initramfs-tools/hooks",
  "tools/pi-image/stage4-octessera/files/root/etc/initramfs-tools/scripts",
  "tools/pi-image/stage4-octessera/files/root/usr/local/bin",
  "tools/pi-image/stage4-octessera/files/root/usr/local/sbin",
  "userpatches/overlay/etc/initramfs-tools/hooks",
  "userpatches/overlay/etc/initramfs-tools/scripts",
  "userpatches/overlay/usr/local/sbin",
]);

const thresholds = {
  fileLocWarn: 300,
  fileLocFail: 500,
  fnLocWarn: 60,
  fnLocHard: 90,
  complexityWarn: 10,
  paramsWarn: 4,
  paramsHard: 6
};

const requiredPiImageAssets = [
  "tools/storage/octessera-sd-card",
  "tools/storage/octessera-sd-card-lib.sh",
  "tools/pi-image/stage4-octessera/files/root/etc/systemd/system/octessera-sd-card.service",
  "tools/pi-image/stage4-octessera/files/root/etc/udev/rules.d/99-octessera-sd-card.rules"
];

function isExcludedAuditPath(path) {
  const rel = relative(ROOT, path).replace(/\\/g, "/");
  for (const root of EXCLUDED_AUDIT_ROOTS) {
    if (rel === root || rel.startsWith(`${root}/`)) return true;
  }
  return false;
}

function isDeploymentScriptPath(path) {
  return [...DEPLOYMENT_SCRIPT_ROOTS].some(
    (root) => path === root || path.startsWith(`${root}/`),
  );
}

function isIncludedFile(path) {
  if (INCLUDE_EXT.has(extname(path))) return true;
  if (extname(path) !== "") return false;
  const rel = relative(ROOT, path).replace(/\\/g, "/");
  return isDeploymentScriptPath(rel) || readFileSync(path, "utf8").startsWith("#!");
}

function listFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (isExcludedAuditPath(full)) continue;
    const st = statSync(full);
    if (st.isDirectory()) {
      if (IGNORE_DIRS.has(entry)) continue;
      out.push(...listFiles(full));
      continue;
    }
    if (!isIncludedFile(full)) continue;
    out.push(full);
  }
  return out;
}

function lineCount(text) {
  const lines = text.split(/\r?\n/);
  return lines[lines.length - 1] === "" ? lines.length - 1 : lines.length;
}

const files = listFiles(ROOT);
const britishSpellingToken = "behavio" + "ur";
const fileStats = [];
const fnStats = [];
const jsComplexityStats = [];
const namingHits = [];

for (const file of files) {
  const rel = relative(ROOT, file).replace(/\\/g, "/");
  const text = readFileSync(file, "utf8");
  const ext = extname(file);
  const loc = lineCount(text);
  fileStats.push({ file: rel, loc });
  let fns = [];
  if (ext === ".rs") {
    fns = scanApproximateRustFunctions(text);
  } else if (JAVASCRIPT_EXT.has(ext)) {
    try {
      fns = scanJavaScriptFunctions(text, ext);
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      throw new Error(
        `Quality audit failed: Babel AST parse failed for JavaScript/TypeScript file ${rel}: ${message}`,
      );
    }
  }
  const functions = fns.map((f) => ({
    ...f,
    file: rel,
    complexityEligible: JAVASCRIPT_EXT.has(ext),
  }));
  fnStats.push(...functions);
  if (JAVASCRIPT_EXT.has(ext)) jsComplexityStats.push(...functions);

  const spellingHits = (text.match(new RegExp(`\\b${britishSpellingToken}\\b`, "gi")) || []).length;
  if (spellingHits > 0) namingHits.push({ file: rel, token: britishSpellingToken, count: spellingHits });
}

const largeFiles = fileStats.filter((f) => f.loc > thresholds.fileLocWarn).sort((a, b) => b.loc - a.loc);
const fileLimitViolations = fileStats.filter((f) => f.loc > thresholds.fileLocFail).sort((a, b) => b.loc - a.loc);
const complexFns = jsComplexityStats.filter((f) => f.complexity > thresholds.complexityWarn).sort((a, b) => b.complexity - a.complexity);
const longFns = fnStats.filter((f) => f.loc > thresholds.fnLocWarn).sort((a, b) => b.loc - a.loc);
const wideFns = fnStats.filter((f) => f.paramCount > thresholds.paramsWarn).sort((a, b) => b.paramCount - a.paramCount);

const report = [];
const missingPiImageAssets = requiredPiImageAssets.filter((file) => !existsSync(join(ROOT, file)));
if (missingPiImageAssets.length > 0) {
  console.error(`Missing required Pi image assets:\n${missingPiImageAssets.map((file) => `- ${file}`).join("\n")}`);
  process.exit(1);
}
report.push("# Code Quality Baseline");
report.push("");
report.push("## Standards");
report.push(`- File LOC: warning at > ${thresholds.fileLocWarn}; failure at > ${thresholds.fileLocFail} (enforced)`);
report.push(`- Function LOC: warning at > ${thresholds.fnLocWarn} (informational; staged hard threshold > ${thresholds.fnLocHard} is not enforced)`);
report.push(`- JavaScript/TypeScript cyclomatic complexity: failure at > ${thresholds.complexityWarn} (enforced)`);
report.push(`- Function params: warning at > ${thresholds.paramsWarn} (informational; staged hard threshold > ${thresholds.paramsHard} is not enforced)`);
report.push("");
report.push("## Summary");
report.push(`- Files scanned: ${fileStats.length}`);
report.push(`- Functions scanned (executable function nodes): ${fnStats.length}`);
report.push(`- Files above warning threshold (> ${thresholds.fileLocWarn} LOC): ${largeFiles.length}`);
report.push(`- Files over enforced limit (> ${thresholds.fileLocFail} LOC): ${fileLimitViolations.length}`);
report.push(`- JavaScript/TypeScript functions over enforced complexity limit (> ${thresholds.complexityWarn}): ${complexFns.length}`);
report.push(`- Long functions (> ${thresholds.fnLocWarn} LOC): ${longFns.length}`);
report.push(`- Wide signatures (> ${thresholds.paramsWarn} params): ${wideFns.length}`);
report.push("");

report.push("## Top File LOC Warnings");
for (const f of largeFiles.slice(0, 20)) report.push(`- ${f.file}: ${f.loc} LOC`);
report.push("");

report.push("## JavaScript/TypeScript Complexity Failures");
for (const f of complexFns) report.push(`- ${f.file}:${f.start} ${f.name}() complexity=${f.complexity}, loc=${f.loc}`);
report.push("");

report.push("## Top Long Functions");
for (const f of longFns.slice(0, 20)) {
  const complexity = f.complexityEligible ? `, complexity=${f.complexity}` : "";
  report.push(`- ${f.file}:${f.start} ${f.name}() loc=${f.loc}${complexity}`);
}
report.push("");

report.push(`## Naming Consistency (behavior vs ${britishSpellingToken})`);
if (namingHits.length === 0) {
  report.push(`- No \`${britishSpellingToken}\` identifier tokens found.`);
} else {
  for (const n of namingHits) report.push(`- ${n.file}: ${n.count} occurrences of '${britishSpellingToken}'`);
}
report.push("");

console.log(report.join("\n"));

if (complexFns.length > 0) {
  console.error(`Quality audit failed: ${complexFns.length} JavaScript/TypeScript function(s) exceed the enforced > ${thresholds.complexityWarn} complexity limit.`);
  for (const f of complexFns) console.error(`- ${f.file}:${f.start} ${f.name}() complexity=${f.complexity}, loc=${f.loc}`);
}

if (fileLimitViolations.length > 0) {
  console.error(`Quality audit failed: ${fileLimitViolations.length} file(s) exceed the enforced > ${thresholds.fileLocFail} LOC limit.`);
  for (const f of fileLimitViolations) console.error(`- ${f.file}: ${f.loc} LOC`);
}

if (complexFns.length > 0 || fileLimitViolations.length > 0) {
  process.exitCode = 1;
}
