#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC2034
contract_path="$script_dir/../../resources/image-construction/boot-layers/raspberry-pi-zero-2w.json"
# shellcheck source=tools/pi-image/verify-boot-layout.sh
source "$script_dir/verify-boot-layout.sh"

fixture="$(mktemp -d)"
trap 'rm -rf "$fixture"' EXIT

reset_fixture() {
    rm -rf "$fixture"
    mkdir -p "$fixture/boot" "$fixture/root"
}

write_constructor_fat_pair() {
    printf '%s\n' '# --- octessera additions ---' '# octessera hardware configuration' '[all]' 'dtoverlay=disable-bt' 'enable_uart=0' > "$fixture/boot/config.txt"
    printf '%s\n' 'console=tty1 root=/dev/mmcblk0p2' > "$fixture/boot/cmdline.txt"
}

write_constructor_redirect_pair() {
    printf '%s\n\n%s\n' 'DO NOT EDIT THIS FILE' 'The file you are looking for has moved to /boot/firmware/config.txt' > "$fixture/root/boot/config.txt"
    printf '%s\n\n%s\n' 'DO NOT EDIT THIS FILE' 'The file you are looking for has moved to /boot/firmware/cmdline.txt' > "$fixture/root/boot/cmdline.txt"
}

expect_constructor_identity_failure() {
    if require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"; then
        echo "$1" >&2
        exit 1
    fi
}

expect_boot_config_failure() {
    if require_octessera_boot_config "$fixture/boot" "$fixture/root"; then
        echo "$1" >&2
        exit 1
    fi
}
