#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
contract_path="$script_dir/../../resources/image-construction/boot-layers/raspberry-pi-zero-2w.json"
# shellcheck disable=SC1091
source "$script_dir/verify-boot-layout.sh"

fixture="$(mktemp -d)"
trap 'rm -rf "$fixture"' EXIT

reset_fixture() {
    rm -rf "$fixture"
    mkdir -p "$fixture/boot" "$fixture/root"
}

write_constructor_fat_pair() {
    printf '%s\n' '# --- octessera additions ---' '# octessera hardware configuration' '[all]' 'dtoverlay=disable-bt' 'enable_uart=0' > "$fixture/boot/config.txt"
    printf '%s\n' 'console=tty1 root=/dev/mmcblk0p2' > "$fixture/boot/cmdline.txt"
}

write_constructor_redirect_pair() {
    printf '%s\n\n%s\n' 'DO NOT EDIT THIS FILE' 'The file you are looking for has moved to /boot/firmware/config.txt' > "$fixture/root/boot/config.txt"
    printf '%s\n\n%s\n' 'DO NOT EDIT THIS FILE' 'The file you are looking for has moved to /boot/firmware/cmdline.txt' > "$fixture/root/boot/cmdline.txt"
}

expect_constructor_identity_failure() {
    if require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"; then
        echo "$1" >&2
        exit 1
    fi
}

expect_boot_config_failure() {
    if require_octessera_boot_config "$fixture/boot" "$fixture/root"; then
        echo "$1" >&2
        exit 1
    fi
}

reset_fixture
mkdir -p "$fixture/boot/octessera/overlays"
printf '%s\n' '# --- octessera additions ---' > "$fixture/boot/config.txt"
printf '%s\n' 'dtbo' > "$fixture/boot/octessera/overlays/i2s-dac-no20.dtbo"
require_octessera_boot_config "$fixture/boot" "$fixture/root"
require_octessera_boot_overlay "$fixture/boot" "$fixture/root"

reset_fixture
mkdir -p "$fixture/root/boot/firmware/octessera/overlays"
printf '%s\n' '# --- octessera additions ---' > "$fixture/root/boot/firmware/config.txt"
printf '%s\n' 'dtbo' > "$fixture/root/boot/firmware/octessera/overlays/i2s-dac-no20.dtbo"
if require_octessera_boot_config "$fixture/boot" "$fixture/root"; then
    echo 'Boot layout accepted a hidden rootfs config marker.' >&2
    exit 1
fi
require_octessera_boot_overlay "$fixture/boot" "$fixture/root"

reset_fixture
if require_octessera_boot_config "$fixture/boot" "$fixture/root"; then
    echo 'Boot layout accepted a missing config marker.' >&2
    exit 1
fi
if require_octessera_boot_overlay "$fixture/boot" "$fixture/root"; then
    echo 'Boot layout accepted a missing overlay.' >&2
    exit 1
fi

if [ "$(id -u)" -eq 0 ]; then
    reset_fixture
    mkdir -p \
        "$fixture/root/etc/profile.d" \
        "$fixture/root/etc/systemd/system/getty.target.wants" \
        "$fixture/root/etc/systemd/system" \
        "$fixture/root/etc/systemd/system/multi-user.target.wants" \
        "$fixture/root/boot" \
        "$fixture/root/home/pi" \
        "$fixture/root/usr/local/lib/octessera" \
        "$fixture/root/etc/systemd/system/multi-user.target.wants"
    printf '%s\n' 'root:x:0:0:root:/root:/bin/bash' 'pi:x:1000:1000:Pi:/home/pi:/bin/bash' > "$fixture/root/etc/passwd"
    printf '%s\n' 'root:x:0:' 'pi:x:1000:' > "$fixture/root/etc/group"
    cp "$script_dir/stage4-octessera/files/root/etc/profile.d/octessera-welcome.sh" "$fixture/root/etc/profile.d/octessera-welcome.sh"
    chmod 0644 "$fixture/root/etc/profile.d/octessera-welcome.sh"
    : > "$fixture/root/home/pi/.hushlogin"
    chown 1000:1000 "$fixture/root/home/pi/.hushlogin"
    write_constructor_fat_pair
    write_constructor_redirect_pair
    for unit in serial0 ttyAMA0 ttyS0; do
        ln -s /dev/null "$fixture/root/etc/systemd/system/serial-getty@$unit.service"
    done
    test ! -e "$fixture/root/etc/systemd/system/multi-user.target.wants/bluetooth.service"
    test ! -e "$fixture/root/etc/systemd/system/multi-user.target.wants/hciuart.service"
    python3 "$script_dir/../legal/stage_notices.py" \
        --repository-root "$script_dir/../.." \
        --destination-root "$fixture/root" >/dev/null
    rm "$fixture/root/usr/share/doc/octessera/licenses/cargo/vendored-cpal-0.15.3/LICENSE"
    ln "$fixture/root/usr/share/doc/octessera/licenses/cargo/reference/Apache-2.0.txt" \
        "$fixture/root/usr/share/doc/octessera/licenses/cargo/vendored-cpal-0.15.3/LICENSE"
    rm "$fixture/root/usr/share/doc/octessera/licenses/pnpm/react/18.3.1/LICENSE" \
        "$fixture/root/usr/share/doc/octessera/licenses/pnpm/scheduler/0.23.2/LICENSE"
    ln "$fixture/root/usr/share/doc/octessera/licenses/pnpm/react-dom/18.3.1/LICENSE" \
        "$fixture/root/usr/share/doc/octessera/licenses/pnpm/react/18.3.1/LICENSE"
    ln "$fixture/root/usr/share/doc/octessera/licenses/pnpm/react-dom/18.3.1/LICENSE" \
        "$fixture/root/usr/share/doc/octessera/licenses/pnpm/scheduler/0.23.2/LICENSE"
    mkdir -p "$fixture/root/usr/share/common-licenses" "$fixture/root/usr/share/doc/base-files"
    printf '%s\n' 'fixture GPL license' > "$fixture/root/usr/share/common-licenses/GPL-3"
    printf '%s\n' 'fixture base-files copyright' > "$fixture/root/usr/share/doc/base-files/copyright"
    require_octessera_legal_notices "$fixture/root"
    ln "$fixture/root/usr/share/doc/octessera/licenses/cargo/reference/Apache-2.0.txt" \
        "$fixture/root/usr/share/doc/external-octessera-legal-alias"
    if require_octessera_legal_notices "$fixture/root"; then
        echo 'Finalized legal verification accepted an external hardlink alias.' >&2
        exit 1
    fi
    rm "$fixture/root/usr/share/doc/external-octessera-legal-alias"
    require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"
    write_constructor_fat_pair
    printf '\r' >> "$fixture/boot/config.txt"
    if require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"; then
        echo 'Boot layout accepted a lone carriage return in config.txt.' >&2
        exit 1
    fi
    write_constructor_fat_pair
    for token in console=serial01 console=ttyAMA0-debug console=ttyS0foo; do
        printf '%s\n' "console=tty1 $token root=/dev/mmcblk0p2" > "$fixture/boot/cmdline.txt"
        require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"
    done
    printf '%s\n' 'console=tty1 console=serial0,115200 root=/dev/mmcblk0p2' > "$fixture/boot/cmdline.txt"
    if require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"; then
        echo 'Boot layout accepted an exact serial console token.' >&2
        exit 1
    fi
    printf '%s\n' 'console=tty1 root=/dev/mmcblk0p2' > "$fixture/boot/cmdline.txt"
    export OCTESSERA_BOOT_LAYER_CLASSIFICATION=constructor-required
    require_octessera_raspberry_identity_for_boot_layer "$fixture/boot" "$fixture/root"

    mkdir -p "$fixture/root/boot/firmware"
    ln "$fixture/boot/config.txt" "$fixture/root/boot/firmware/config.txt"
    ln "$fixture/boot/cmdline.txt" "$fixture/root/boot/firmware/cmdline.txt"
    require_octessera_raspberry_identity "$fixture/boot" "$fixture/root"
    rm -rf "$fixture/root/boot/firmware"

    mkdir -p "$fixture/root/boot/firmware"
    cp "$fixture/boot/config.txt" "$fixture/root/boot/firmware/config.txt"
    cp "$fixture/boot/cmdline.txt" "$fixture/root/boot/firmware/cmdline.txt"
    expect_constructor_identity_failure 'Constructor identity accepted independent same-byte firmware duplicates.'
    rm -rf "$fixture/root/boot/firmware"

    mkdir -p "$fixture/root/boot/firmware"
    ln "$fixture/boot/config.txt" "$fixture/root/boot/firmware/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a partial raw firmware pair.'
    rm -rf "$fixture/root/boot/firmware"

    mkdir -p "$fixture/root/boot/firmware"
    ln "$fixture/boot/config.txt" "$fixture/root/boot/firmware/config.txt"
    cp "$fixture/boot/cmdline.txt" "$fixture/root/boot/firmware/cmdline.txt"
    expect_constructor_identity_failure 'Constructor identity accepted mixed raw firmware objects.'
    rm -rf "$fixture/root/boot/firmware"

    for path in config.txt cmdline.txt; do
        rm "$fixture/root/boot/$path"
        expect_constructor_identity_failure "Constructor identity accepted a missing rootfs redirect notice: $path"
        write_constructor_redirect_pair
    done
    printf '%s\n\n%s\n' 'DO NOT EDIT THIS FILE' 'The file you are looking for has moved to /boot/firmware/config.txt altered' > "$fixture/root/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted an altered rootfs config redirect notice.'
    write_constructor_redirect_pair
    chmod 0600 "$fixture/root/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a rootfs redirect notice with the wrong mode.'
    chmod 0644 "$fixture/root/boot/config.txt"
    rm "$fixture/root/boot/config.txt"
    mkdir "$fixture/root/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a non-regular rootfs config redirect notice.'
    rmdir "$fixture/root/boot/config.txt"
    write_constructor_redirect_pair
    rm "$fixture/root/boot/config.txt"
    ln -s "$fixture/boot/config.txt" "$fixture/root/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a symlinked rootfs config redirect notice.'
    rm "$fixture/root/boot/config.txt"
    write_constructor_redirect_pair

    rm "$fixture/boot/config.txt"
    mkdir -p "$fixture/root/boot/firmware"
    printf '%s\n' '# --- octessera additions ---' > "$fixture/root/boot/firmware/config.txt"
    expect_boot_config_failure 'Boot config accepted a hidden marker for a missing FAT config.'
    expect_constructor_identity_failure 'Constructor identity accepted a missing FAT config with a hidden marker.'
    rm -rf "$fixture/root/boot/firmware"
    write_constructor_fat_pair
    mkdir -p "$fixture/root/boot/firmware"
    cp "$fixture/boot/cmdline.txt" "$fixture/root/boot/firmware/cmdline.txt"
    rm "$fixture/boot/cmdline.txt"
    expect_constructor_identity_failure 'Constructor identity paired a FAT config with a raw firmware cmdline.'
    rm -rf "$fixture/root/boot/firmware"
    write_constructor_fat_pair
    rm "$fixture/boot/config.txt"
    mkdir "$fixture/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a non-regular FAT config.'
    rmdir "$fixture/boot/config.txt"
    write_constructor_fat_pair
    rm "$fixture/boot/config.txt"
    ln -s "$fixture/boot/cmdline.txt" "$fixture/boot/config.txt"
    expect_constructor_identity_failure 'Constructor identity accepted a symlinked FAT config.'
    rm "$fixture/boot/config.txt"
    write_constructor_fat_pair

    printf '%s\n' '# octessera hardware configuration' '[all]' 'dtoverlay=disable-bt' 'enable_uart=0' > "$fixture/boot/config.txt"
    mkdir -p "$fixture/root/boot/firmware"
    printf '%s\n' '# --- octessera additions ---' > "$fixture/root/boot/firmware/config.txt"
    expect_boot_config_failure 'Boot config accepted a hidden marker for a marker-less FAT config.'
    expect_constructor_identity_failure 'Constructor identity accepted a marker-less FAT config with hidden firmware content.'
    rm -rf "$fixture/root/boot/firmware"
    printf '%s\n' '# octessera hardware configuration' '[all]' 'dtoverlay=disable-bt' 'enable_uart=0' > "$fixture/boot/config.txt"
    expect_boot_config_failure 'Boot config accepted a marker-less FAT config.'
    write_constructor_fat_pair

    create_trusted_parent_fixture() {
        reset_fixture
        mkdir -p \
            "$fixture/boot/octessera/overlays" \
            "$fixture/root/etc/profile.d" \
            "$fixture/root/etc/systemd/system/sysinit.target.wants" \
            "$fixture/root/etc/systemd/system/getty.target.wants" \
            "$fixture/root/etc/systemd/system/multi-user.target.wants" \
            "$fixture/root/home/pi" \
            "$fixture/root/boot/firmware" \
            "$fixture/root/usr/local/lib/octessera"
        cp "$script_dir/fixtures/trusted-parent-v0.7.5/boot/config.txt" "$fixture/boot/config.txt"
        cp "$script_dir/fixtures/trusted-parent-v0.7.5/boot/cmdline.txt" "$fixture/boot/cmdline.txt"
        cp "$script_dir/fixtures/trusted-parent-v0.7.5/root/boot/config.txt" "$fixture/root/boot/config.txt"
        chmod 0755 "$fixture/boot/config.txt" "$fixture/boot/cmdline.txt"
        chmod 0644 "$fixture/root/boot/config.txt"
        printf '%s\n' 'dtbo' > "$fixture/boot/octessera/overlays/i2s-dac-no20.dtbo"
        cat > "$fixture/root/etc/systemd/system/octessera-boot-splash.service" <<'EOF'
[Unit]
Description=legacy boot splash
After=systemd-modules-load.service systemd-udevd.service
Before=sysinit.target octessera.service

[Service]
Type=oneshot
ExecStart=-/usr/local/bin/octessera-pi --boot-splash-once
TimeoutStartSec=2

[Install]
WantedBy=sysinit.target
EOF
        cat > "$fixture/root/etc/systemd/system/octessera.service" <<'EOF'
[Unit]
Description=legacy Octessera runtime

[Service]
Type=simple
ExecStart=/usr/local/bin/octessera-pi
EOF
        chmod 0644 \
            "$fixture/root/etc/systemd/system/octessera-boot-splash.service" \
            "$fixture/root/etc/systemd/system/octessera.service"
        ln -s ../octessera-boot-splash.service "$fixture/root/etc/systemd/system/sysinit.target.wants/octessera-boot-splash.service"
        printf '%s\n' 'root:x:0:0:root:/root:/bin/bash' 'pi:x:1000:1000:Pi:/home/pi:/bin/bash' > "$fixture/root/etc/passwd"
        printf '%s\n' 'root:x:0:' 'pi:x:1000:' > "$fixture/root/etc/group"
        printf '%s\n' 'legacy parent welcome' > "$fixture/root/etc/profile.d/octessera-welcome.sh"
        chmod 0644 "$fixture/root/etc/profile.d/octessera-welcome.sh"
        python3 "$script_dir/../legal/stage_notices.py" \
            --repository-root "$script_dir/../.." \
            --destination-root "$fixture/root" >/dev/null
        mkdir -p "$fixture/root/usr/share/common-licenses" "$fixture/root/usr/share/doc/base-files"
        printf '%s\n' 'fixture GPL license' > "$fixture/root/usr/share/common-licenses/GPL-3"
        printf '%s\n' 'fixture base-files copyright' > "$fixture/root/usr/share/doc/base-files/copyright"
    }

    create_trusted_parent_fixture
    require_octessera_boot_config "$fixture/boot" "$fixture/root"
    require_octessera_boot_overlay "$fixture/boot" "$fixture/root"
    require_octessera_boot_layer "$fixture/boot" "$fixture/root"
    require_octessera_raspberry_identity_for_boot_layer "$fixture/boot" "$fixture/root"
fi

reset_fixture
mkdir -p \
    "$fixture/root/etc/initramfs-tools/scripts/init-premount" \
    "$fixture/root/opt/octessera/releases/1.2.3" \
    "$fixture/root/usr/local/bin" \
    "$fixture/archive/scripts/init-premount" \
    "$fixture/archive/usr/local/bin" \
    "$fixture/archive/usr/bin"
cp "$script_dir/stage4-octessera/files/root/etc/initramfs-tools/scripts/init-premount/octessera-boot-splash" \
    "$fixture/root/etc/initramfs-tools/scripts/init-premount/octessera-boot-splash"
chmod 0755 "$fixture/root/etc/initramfs-tools/scripts/init-premount/octessera-boot-splash"
cp "$fixture/root/etc/initramfs-tools/scripts/init-premount/octessera-boot-splash" \
    "$fixture/archive/scripts/init-premount/octessera-boot-splash"
chmod 0755 "$fixture/archive/scripts/init-premount/octessera-boot-splash"
printf '%s\n' 'constructor-runtime-binary' > "$fixture/root/opt/octessera/releases/1.2.3/octessera-pi"
chmod 0755 "$fixture/root/opt/octessera/releases/1.2.3/octessera-pi"
cp "$fixture/root/opt/octessera/releases/1.2.3/octessera-pi" "$fixture/archive/usr/local/bin/octessera-pi"
ln -s /opt/octessera/releases/1.2.3 "$fixture/root/opt/octessera/current"
ln -s /opt/octessera/current/octessera-pi "$fixture/root/usr/local/bin/octessera-pi"
ln -s usr/bin "$fixture/archive/bin"
ln -s dash "$fixture/archive/usr/bin/sh"
for archive_entry in \
    usr/bin/dash \
    usr/bin/setsid \
    usr/bin/sleep \
    usr/bin/cat \
    usr/bin/mv \
    usr/bin/chmod \
    usr/bin/chown \
    usr/bin/rm; do
    mkdir -p "$fixture/archive/${archive_entry%/*}"
    printf '%s\n' "fixture-$archive_entry" > "$fixture/archive/$archive_entry"
    chmod 0755 "$fixture/archive/$archive_entry"
done
mkdir -p "$fixture/archive/lib/modules/fixture/kernel/drivers/spi"
for required_module in spi-bcm2835 spidev; do
    printf '%s\n' "fixture-$required_module" > "$fixture/archive/lib/modules/fixture/kernel/drivers/spi/$required_module.ko"
done
make_initramfs() {
    local output="$fixture/boot/octessera-bound.img"
    mkdir -p "$fixture/boot"
    (cd "$fixture/archive" && find . -print | cpio -o -H newc --quiet | gzip -n > "$output")
}
make_initramfs
require_octessera_initramfs_rootfs_bindings "$fixture/boot/octessera-bound.img" "$fixture/root" "$contract_path"
printf '%s\n' 'stale-script' > "$fixture/archive/scripts/init-premount/octessera-boot-splash"
make_initramfs
if require_octessera_initramfs_rootfs_bindings "$fixture/boot/octessera-bound.img" "$fixture/root" "$contract_path"; then
    echo 'Boot layout accepted a stale initramfs script.' >&2
    exit 1
fi
cp "$fixture/root/etc/initramfs-tools/scripts/init-premount/octessera-boot-splash" "$fixture/archive/scripts/init-premount/octessera-boot-splash"
printf '%s\n' 'stale-binary' > "$fixture/archive/usr/local/bin/octessera-pi"
make_initramfs
if require_octessera_initramfs_rootfs_bindings "$fixture/boot/octessera-bound.img" "$fixture/root" "$contract_path"; then
    echo 'Boot layout accepted a stale initramfs binary.' >&2
    exit 1
fi
cp "$fixture/root/opt/octessera/releases/1.2.3/octessera-pi" "$fixture/archive/usr/local/bin/octessera-pi"
make_initramfs
mkdir -p "$fixture/boot/octessera" "$fixture/lsinitramfs-bin"
cp "$fixture/boot/octessera-bound.img" "$fixture/boot/octessera/initrd.img-1.2.3"
cat > "$fixture/lsinitramfs-bin/lsinitramfs" <<'EOF'
#!/usr/bin/env bash
if [ "${1:-}" = -l ]; then
    while IFS= read -r entry; do
        case "$entry" in
            bin)
                target="${OCTESSERA_TEST_BIN_TARGET:-usr/bin}"
                printf '%s\n' "lrwxrwxrwx 1 root root ${#target} Jan 1 1970 bin -> $target" ;;
            usr/bin/sh)
                target="${OCTESSERA_TEST_SH_TARGET:-dash}"
                printf '%s\n' "lrwxrwxrwx 1 root root ${#target} Jan 1 1970 usr/bin/sh -> $target" ;;
            bin/*)
                case "${OCTESSERA_TEST_LEGACY_TYPE:-regular}" in
                    symlink) printf '%s\n' "lrwxrwxrwx 1 root root 8 Jan 1 1970 $entry -> usr/bin" ;;
                    directory) printf '%s\n' "drwxr-xr-x 1 root root 0 Jan 1 1970 $entry" ;;
                    device) printf '%s\n' "crw-rw-rw- 1 root root 0 Jan 1 1970 $entry" ;;
                    hardlink) printf '%s\n' "-rwxr-xr-x 2 root root 8 Jan 1 1970 $entry" ;;
                    *) printf '%s\n' "-rwxr-xr-x 1 root root 8 Jan 1 1970 $entry" ;;
                esac ;;
            usr/bin/sleep)
                printf '%s\n' "${OCTESSERA_TEST_ENTRY_MODE:-$(printf '%s' -rwxr-xr-x)} ${OCTESSERA_TEST_ENTRY_LINKS:-1} root root ${OCTESSERA_TEST_ENTRY_SIZE:-$(stat -c '%s' "$OCTESSERA_TEST_INITRAMFS_ARCHIVE_ROOT/$entry")} Jan 1 1970 $entry" ;;
            *)
                size=1
                if [ -e "$OCTESSERA_TEST_INITRAMFS_ARCHIVE_ROOT/$entry" ] && [ ! -L "$OCTESSERA_TEST_INITRAMFS_ARCHIVE_ROOT/$entry" ]; then
                    size="$(stat -c '%s' "$OCTESSERA_TEST_INITRAMFS_ARCHIVE_ROOT/$entry")"
                fi
                printf '%s\n' "-rwxr-xr-x 1 root root $size Jan 1 1970 $entry" ;;
        esac
    done < "$OCTESSERA_TEST_INITRAMFS_LISTING"
else
    cat "$OCTESSERA_TEST_INITRAMFS_LISTING"
fi
EOF
chmod 0755 "$fixture/lsinitramfs-bin/lsinitramfs"
listing="$fixture/initramfs-listing"
cat > "$listing" <<'EOF'
scripts/init-premount/octessera-boot-splash
usr/local/bin/octessera-pi
bin
usr/bin/sh
usr/bin/dash
usr/bin/setsid
usr/bin/sleep
usr/bin/cat
usr/bin/mv
usr/bin/chmod
usr/bin/chown
usr/bin/rm
lib/modules/fixture/kernel/drivers/spi/spi-bcm2835.ko
lib/modules/fixture/kernel/drivers/spi/spidev.ko
EOF
for ((index = 1; index <= 8192; index++)); do
    printf 'usr/lib/fixture-trailing/%04d\n' "$index" >> "$listing"
done
export OCTESSERA_TEST_INITRAMFS_LISTING="$listing"
export OCTESSERA_TEST_INITRAMFS_ARCHIVE_ROOT="$fixture/archive"
export PATH="$fixture/lsinitramfs-bin:$PATH"
require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"

for target_case in wrong absolute escaping cyclic; do
    case "$target_case" in
        wrong) export OCTESSERA_TEST_BIN_TARGET=wrong ;;
        absolute) export OCTESSERA_TEST_BIN_TARGET=/usr/bin ;;
        escaping) export OCTESSERA_TEST_BIN_TARGET=../usr/bin ;;
        cyclic) export OCTESSERA_TEST_BIN_TARGET=bin ;;
    esac
    if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
        echo "Boot layout accepted $target_case bin symlink target." >&2
        exit 1
    fi
    unset OCTESSERA_TEST_BIN_TARGET
done

for target_case in wrong absolute escaping cyclic; do
    case "$target_case" in
        wrong) export OCTESSERA_TEST_SH_TARGET=wrong ;;
        absolute) export OCTESSERA_TEST_SH_TARGET=/bin/sh ;;
        escaping) export OCTESSERA_TEST_SH_TARGET=../sh ;;
        cyclic) export OCTESSERA_TEST_SH_TARGET=sh ;;
    esac
    if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
        echo "Boot layout accepted $target_case usr/bin/sh symlink target." >&2
        exit 1
    fi
    unset OCTESSERA_TEST_SH_TARGET
done

for command_entry in usr/bin/dash usr/bin/setsid usr/bin/sleep usr/bin/cat usr/bin/mv usr/bin/chmod usr/bin/chown usr/bin/rm; do
    altered_listing="$fixture/missing-${command_entry##*/}-listing"
    sed "\|^$command_entry$|d" "$listing" > "$altered_listing"
    export OCTESSERA_TEST_INITRAMFS_LISTING="$altered_listing"
    if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
        echo "Boot layout accepted a missing command target: $command_entry" >&2
        exit 1
    fi
done

for invalid_case in zero non-executable non-regular device hardlink oversized; do
    export OCTESSERA_TEST_ENTRY_MODE=-rwxr-xr-x
    export OCTESSERA_TEST_ENTRY_LINKS=1
    export OCTESSERA_TEST_ENTRY_SIZE=8
    case "$invalid_case" in
        zero) export OCTESSERA_TEST_ENTRY_SIZE=0 ;;
        non-executable) export OCTESSERA_TEST_ENTRY_MODE=-rw-r--r-- ;;
        non-regular) export OCTESSERA_TEST_ENTRY_MODE=drwxr-xr-x; export OCTESSERA_TEST_ENTRY_SIZE=0 ;;
        device) export OCTESSERA_TEST_ENTRY_MODE=crw-rw-rw-; export OCTESSERA_TEST_ENTRY_SIZE=0 ;;
        hardlink) export OCTESSERA_TEST_ENTRY_LINKS=2 ;;
        oversized) export OCTESSERA_TEST_ENTRY_SIZE=67108865 ;;
    esac
    export OCTESSERA_TEST_INITRAMFS_LISTING="$listing"
    if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
        echo "Boot layout accepted an invalid command target: $invalid_case" >&2
        exit 1
    fi
    unset OCTESSERA_TEST_ENTRY_MODE OCTESSERA_TEST_ENTRY_LINKS OCTESSERA_TEST_ENTRY_SIZE
done

for legacy_entry in bin/sh bin/dash bin/setsid bin/sleep bin/cat bin/mv bin/chmod bin/chown bin/rm bin/unexpected; do
    for legacy_type in regular symlink directory device hardlink; do
        legacy_listing="$fixture/legacy-${legacy_entry##*/}-$legacy_type-listing"
        cp "$listing" "$legacy_listing"
        printf '%s\n' "$legacy_entry" >> "$legacy_listing"
        export OCTESSERA_TEST_INITRAMFS_LISTING="$legacy_listing"
        export OCTESSERA_TEST_LEGACY_TYPE="$legacy_type"
        if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
            echo "Boot layout accepted a legacy $legacy_entry $legacy_type entry." >&2
            exit 1
        fi
        unset OCTESSERA_TEST_LEGACY_TYPE
    done
done

missing_entry_listing="$fixture/missing-entry-listing"
sed '/^usr\/bin\/setsid$/d' "$listing" > "$missing_entry_listing"
export OCTESSERA_TEST_INITRAMFS_LISTING="$missing_entry_listing"
if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
    echo 'Boot layout accepted an initramfs missing a required entry.' >&2
    exit 1
fi

missing_module_listing="$fixture/missing-module-listing"
sed '/spi-bcm2835/d' "$listing" > "$missing_module_listing"
export OCTESSERA_TEST_INITRAMFS_LISTING="$missing_module_listing"
if require_octessera_initramfs_boot_layer "$fixture/boot" "$fixture/root"; then
    echo 'Boot layout accepted an initramfs missing a required module.' >&2
    exit 1
fi

printf '%s\n' 'Sanitized image boot layout tests passed'
