use super::cellular::LifeState;
use super::native_impl::{
    AntState, BoidsState, BounceState, BrainState, BubblesState, CoralState, CracksState,
    CrystalGrowthState, CyclicState, DlaState, ForestFireState, FractalExplorerState, GravityState,
    InkState, IsingState, KeysState, KuramotoState, LavaLampState, LightningState, LooperState,
    MazeGrowthState, OrbitState, PhysarumState, PredatorPreyState, RaindropsState,
    ReactionDiffusionState, RiversState, SandRipplesState, ShapesState, VinesState, WaveState,
};
use super::play::{NoneState, SequencerState};

#[derive(Clone, Debug, PartialEq)]
pub enum NativeBehaviorState {
    None(NoneState),
    Life(LifeState),
    Sequencer(SequencerState),
    Keys(KeysState),
    Looper(LooperState),
    Brain(BrainState),
    Cyclic(CyclicState),
    ForestFire(ForestFireState),
    PredatorPrey(PredatorPreyState),
    Ant(AntState),
    Boids(BoidsState),
    Bounce(BounceState),
    Bubbles(BubblesState),
    Gravity(GravityState),
    LavaLamp(LavaLampState),
    Orbit(OrbitState),
    SandRipples(SandRipplesState),
    FractalExplorer(FractalExplorerState),
    MazeGrowth(MazeGrowthState),
    Shapes(ShapesState),
    Ink(InkState),
    Ising(IsingState),
    Kuramoto(KuramotoState),
    Lightning(LightningState),
    Wave(WaveState),
    Raindrops(RaindropsState),
    ReactionDiffusion(ReactionDiffusionState),
    Rivers(RiversState),
    Cracks(CracksState),
    Coral(CoralState),
    CrystalGrowth(CrystalGrowthState),
    Dla(DlaState),
    Physarum(PhysarumState),
    Vines(VinesState),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NativeBehavior {
    None,
    Life,
    Sequencer,
    Keys,
    Looper,
    Brain,
    Cyclic,
    ForestFire,
    PredatorPrey,
    Ant,
    Boids,
    Bounce,
    Bubbles,
    Gravity,
    LavaLamp,
    Orbit,
    SandRipples,
    FractalExplorer,
    MazeGrowth,
    Shapes,
    Ink,
    Ising,
    Kuramoto,
    Lightning,
    Wave,
    Raindrops,
    ReactionDiffusion,
    Rivers,
    Cracks,
    Coral,
    CrystalGrowth,
    Dla,
    Physarum,
    Vines,
}

pub fn get_native_behavior(id: &str) -> Option<NativeBehavior> {
    match id {
        "none" => Some(NativeBehavior::None),
        "life" => Some(NativeBehavior::Life),
        "sequencer" => Some(NativeBehavior::Sequencer),
        "keys" => Some(NativeBehavior::Keys),
        "looper" => Some(NativeBehavior::Looper),
        "brain" => Some(NativeBehavior::Brain),
        "cyclic" => Some(NativeBehavior::Cyclic),
        "forest_fire" => Some(NativeBehavior::ForestFire),
        "predator_prey" => Some(NativeBehavior::PredatorPrey),
        "ant" => Some(NativeBehavior::Ant),
        "boids" => Some(NativeBehavior::Boids),
        "bounce" => Some(NativeBehavior::Bounce),
        "bubbles" => Some(NativeBehavior::Bubbles),
        "gravity" => Some(NativeBehavior::Gravity),
        "lava_lamp" => Some(NativeBehavior::LavaLamp),
        "orbit" => Some(NativeBehavior::Orbit),
        "sand_ripples" => Some(NativeBehavior::SandRipples),
        "fractal_explorer" => Some(NativeBehavior::FractalExplorer),
        "maze_growth" => Some(NativeBehavior::MazeGrowth),
        "shapes" => Some(NativeBehavior::Shapes),
        "ink" => Some(NativeBehavior::Ink),
        "ising" => Some(NativeBehavior::Ising),
        "kuramoto" => Some(NativeBehavior::Kuramoto),
        "lightning" => Some(NativeBehavior::Lightning),
        "wave" => Some(NativeBehavior::Wave),
        "raindrops" => Some(NativeBehavior::Raindrops),
        "reaction_diffusion" => Some(NativeBehavior::ReactionDiffusion),
        "rivers" => Some(NativeBehavior::Rivers),
        "cracks" => Some(NativeBehavior::Cracks),
        "coral" => Some(NativeBehavior::Coral),
        "crystal_growth" => Some(NativeBehavior::CrystalGrowth),
        "dla" => Some(NativeBehavior::Dla),
        "physarum" => Some(NativeBehavior::Physarum),
        "vines" => Some(NativeBehavior::Vines),
        _ => None,
    }
}

pub fn list_native_behavior_ids() -> &'static [&'static str] {
    &[
        "none",
        "life",
        "sequencer",
        "keys",
        "looper",
        "brain",
        "cyclic",
        "forest_fire",
        "predator_prey",
        "ant",
        "bounce",
        "bubbles",
        "gravity",
        "boids",
        "lava_lamp",
        "orbit",
        "sand_ripples",
        "fractal_explorer",
        "maze_growth",
        "shapes",
        "ink",
        "ising",
        "kuramoto",
        "lightning",
        "raindrops",
        "reaction_diffusion",
        "rivers",
        "wave",
        "cracks",
        "coral",
        "crystal_growth",
        "dla",
        "physarum",
        "vines",
    ]
}

impl NativeBehavior {
    pub fn id(self) -> &'static str {
        match self {
            NativeBehavior::None => "none",
            NativeBehavior::Life => "life",
            NativeBehavior::Sequencer => "sequencer",
            NativeBehavior::Keys => "keys",
            NativeBehavior::Looper => "looper",
            NativeBehavior::Brain => "brain",
            NativeBehavior::Cyclic => "cyclic",
            NativeBehavior::ForestFire => "forest_fire",
            NativeBehavior::PredatorPrey => "predator_prey",
            NativeBehavior::Ant => "ant",
            NativeBehavior::Boids => "boids",
            NativeBehavior::Bounce => "bounce",
            NativeBehavior::Bubbles => "bubbles",
            NativeBehavior::Gravity => "gravity",
            NativeBehavior::LavaLamp => "lava_lamp",
            NativeBehavior::Orbit => "orbit",
            NativeBehavior::SandRipples => "sand_ripples",
            NativeBehavior::FractalExplorer => "fractal_explorer",
            NativeBehavior::MazeGrowth => "maze_growth",
            NativeBehavior::Shapes => "shapes",
            NativeBehavior::Ink => "ink",
            NativeBehavior::Ising => "ising",
            NativeBehavior::Kuramoto => "kuramoto",
            NativeBehavior::Lightning => "lightning",
            NativeBehavior::Wave => "wave",
            NativeBehavior::Raindrops => "raindrops",
            NativeBehavior::ReactionDiffusion => "reaction_diffusion",
            NativeBehavior::Rivers => "rivers",
            NativeBehavior::Cracks => "cracks",
            NativeBehavior::Coral => "coral",
            NativeBehavior::CrystalGrowth => "crystal_growth",
            NativeBehavior::Dla => "dla",
            NativeBehavior::Physarum => "physarum",
            NativeBehavior::Vines => "vines",
        }
    }
}
